; prelude.scm -- the rest of the Z80 Scheme, written in Scheme; loaded one form per line.
; Derived syntax is define-macro over lists; each expansion replaces its call form in place.
(define (caar x) (car (car x)))
(define (cdar x) (cdr (car x)))
(define (cadr x) (car (cdr x)))
(define (cddr x) (cdr (cdr x)))
(define (caddr x) (car (cddr x)))
(define (cdddr x) (cdr (cddr x)))
(define (zero? n) (= n 0))
(define (positive? n) (> n 0))
(define (negative? n) (< n 0))
(define (even? n) (= (remainder n 2) 0))
(define (odd? n) (not (even? n)))
(define (abs n) (if (< n 0) (- n) n))
(define (square x) (* x x))
(define (max x . r) (if (null? r) x (apply max (if (> x (car r)) x (car r)) (cdr r))))
(define (min x . r) (if (null? r) x (apply min (if (< x (car r)) x (car r)) (cdr r))))
(define (gcd2 a b) (if (= b 0) a (gcd2 b (remainder a b))))
(define (gcd . ns) (if (null? ns) 0 (gcd2 (abs (car ns)) (abs (apply gcd (cdr ns))))))
(define (lcm2 a b) (if (= a 0) 0 (if (= b 0) 0 (quotient (* a b) (gcd2 a b)))))
(define (lcm . ns) (if (null? ns) 1 (lcm2 (abs (car ns)) (apply lcm (cdr ns)))))
(define (sqrt n) (define (lp i) (if (> (* i i) n) (- i 1) (lp (+ i 1)))) (lp 0))
(define (floor x) x)
(define (symbol=? a b) (eq? a b))
(define (list? l) (if (null? l) #t (if (pair? l) (list? (cdr l)) #f)))
(define (length l) (define (lp l n) (if (pair? l) (lp (cdr l) (+ n 1)) n)) (lp l 0))
(define (reverse l) (define (lp l a) (if (null? l) a (lp (cdr l) (cons (car l) a)))) (lp l '()))
(define (append2 a b) (define (lp r b) (if (null? r) b (lp (cdr r) (cons (car r) b)))) (lp (reverse a) b))
(define (append . ls) (if (null? ls) '() (if (null? (cdr ls)) (car ls) (append2 (car ls) (apply append (cdr ls))))))
(define (list-tail l k) (if (zero? k) l (list-tail (cdr l) (- k 1))))
(define (list-ref l k) (car (list-tail l k)))
(define (memq x l) (if (null? l) #f (if (eq? x (car l)) l (memq x (cdr l)))))
(define (memv x l) (if (null? l) #f (if (eqv? x (car l)) l (memv x (cdr l)))))
(define (member x l) (if (null? l) #f (if (equal? x (car l)) l (member x (cdr l)))))
(define (assq x l) (if (null? l) #f (if (eq? x (caar l)) (car l) (assq x (cdr l)))))
(define (assv x l) (if (null? l) #f (if (eqv? x (caar l)) (car l) (assv x (cdr l)))))
(define (assoc x l) (if (null? l) #f (if (equal? x (caar l)) (car l) (assoc x (cdr l)))))
(define (map1 f l) (if (null? l) '() (cons (f (car l)) (map1 f (cdr l)))))
(define (map f . ls) (if (null? (cdr ls)) (map1 f (car ls)) (if (null? (car ls)) '() (cons (apply f (map1 car ls)) (apply map f (map1 cdr ls))))))
(define (for-each f l) (if (null? l) #t (begin (f (car l)) (for-each f (cdr l)))))
(define (list-copy l) (map1 (lambda (x) x) l))
(define (make-list n x) (if (zero? n) '() (cons x (make-list (- n 1) x))))
(define-macro when (lambda (f) (list 'if (cadr f) (cons 'begin (cddr f)))))
(define-macro unless (lambda (f) (list 'if (list 'not (cadr f)) (cons 'begin (cddr f)))))
(define (named-let f) (list (list 'lambda '() (list 'define (cadr f) (cons 'lambda (cons (map1 car (caddr f)) (cdddr f)))) (cons (cadr f) (map1 cadr (caddr f))))))
(define-macro let (lambda (f) (if (symbol? (cadr f)) (named-let f) (cons (cons 'lambda (cons (map1 car (cadr f)) (cddr f))) (map1 cadr (cadr f))))))
(define-macro let* (lambda (f) (if (null? (cadr f)) (cons 'let (cons '() (cddr f))) (list 'let (list (car (cadr f))) (cons 'let* (cons (cdr (cadr f)) (cddr f)))))))
(define (letrec-x f) (list (cons 'lambda (cons '() (append (map1 (lambda (b) (cons 'define b)) (cadr f)) (cddr f))))))
(define-macro letrec letrec-x)
(define-macro letrec* letrec-x)
(define-macro and (lambda (f) (if (null? (cdr f)) #t (if (null? (cddr f)) (cadr f) (list 'if (cadr f) (cons 'and (cddr f)) #f)))))
(define-macro or (lambda (f) (if (null? (cdr f)) #f (if (null? (cddr f)) (cadr f) (list 'let (list (list '%t (cadr f))) (list 'if '%t '%t (cons 'or (cddr f))))))))
(define (cond1 c r) (if (eq? (car c) 'else) (cons 'begin (cdr c)) (if (null? (cdr c)) (list 'or (car c) r) (if (eq? (cadr c) '=>) (list 'let (list (list '%c (car c))) (list 'if '%c (list (caddr c) '%c) r)) (list 'if (car c) (cons 'begin (cdr c)) r)))))
(define-macro cond (lambda (f) (if (null? (cdr f)) (list 'if #f #f) (cond1 (cadr f) (cons 'cond (cddr f))))))
(define-macro case (lambda (f) (list 'let (list (list '%k (cadr f))) (cons 'cond (map1 (lambda (c) (if (eq? (car c) 'else) c (cons (list 'memv '%k (list 'quote (car c))) (cdr c)))) (cddr f))))))
(define-macro do (lambda (f) (list 'let '%do (map1 (lambda (b) (list (car b) (cadr b))) (cadr f)) (list 'if (car (caddr f)) (cons 'begin (cdr (caddr f))) (append (cons 'begin (cdddr f)) (list (cons '%do (map1 (lambda (b) (if (null? (cddr b)) (car b) (caddr b))) (cadr f)))))))))
