;;; test-asm.lisp -- layer 2 tests: every instruction form the assembler knows,
;;; assembled by asm.lisp and by the z80pack reference assembler (z80asm);
;;; one instruction per check, bytes must match exactly.
;;; Run: sbcl --script test-asm.lisp   (needs Z80ASM, default ~/src/z80pack/z80asm/z80asm)
(load (merge-pathnames "asm.lisp" *load-truename*))
(in-package :z80)

(defparameter *cases*
  (let ((r8 '(b c d e h l (@ hl) a)) (out '()))
    (flet ((add (f) (push f out)))
      (dolist (x r8) (dolist (y r8) (unless (and (consp x) (consp y)) (add `(ld ,x ,y)))))
      (dolist (x r8) (add `(ld ,x 66)) (add `(inc ,x)) (add `(dec ,x)))
      (dolist (x '(b c d e h l a)) (add `(ld ,x (@ ix 5))) (add `(ld (@ ix -3) ,x)))
      (dolist (op '(add adc sbc)) (dolist (x r8) (add `(,op a ,x))) (add `(,op a 7)) (add `(,op a (@ ix 2))))
      (dolist (op '(sub and xor or cp)) (dolist (x r8) (add `(,op ,x))) (add `(,op 200)) (add `(,op (@ ix 2))))
      (dolist (rr '(bc de hl sp)) (add `(ld ,rr 4660)) (add `(inc ,rr)) (add `(dec ,rr))
        (add `(add hl ,rr)) (add `(adc hl ,rr)) (add `(sbc hl ,rr)) (add `(ld ,rr (@ 4660))) (add `(ld (@ 4660) ,rr)))
      (dolist (rr '(bc de ix sp)) (add `(add ix ,rr)))
      (dolist (rr '(bc de hl af ix)) (add `(push ,rr)) (add `(pop ,rr)))
      (dolist (cc '(nz z nc c po pe p m)) (add `(jp ,cc 4660)) (add `(call ,cc 4660)) (add `(ret ,cc)))
      (dolist (cc '(nz z nc c)) (add `(jr ,cc 0)))
      (dolist (op '(rlc rrc rl rr sla sra srl)) (dolist (x r8) (add `(,op ,x))))
      (dolist (op '(bit res set)) (dolist (n '(0 3 7)) (dolist (x r8) (add `(,op ,n ,x)))))
      (dolist (p '(0 8 16 56)) (add `(rst ,p)))
      (dolist (f '((ld a (@ bc)) (ld a (@ de)) (ld (@ bc) a) (ld (@ de) a) (ld a (@ 4660)) (ld (@ 4660) a)
                   (ld sp hl) (ld sp ix) (ld ix 4660) (ld ix (@ 4660)) (ld (@ 4660) ix) (ld (@ ix 4) 9)
                   (inc ix) (dec ix) (inc (@ ix 1)) (dec (@ ix 1)) (jp 4660) (jp (@ hl)) (jp (@ ix))
                   (call 4660) (jr 0) (djnz 0) (ex de hl) (ex (@ sp) hl) (ex (@ sp) ix) (ex af af)
                   (in a (@ 40)) (out (@ 41) a) (nop) (rlca) (rrca) (rla) (rra) (cpl) (scf) (ccf)
                   (db 1 255 "ab") (dw 4660 1) (halt) (di) (ei) (ret) (exx) (neg) (ldir) (lddr) (cpir)))
        (add f)))
    (nreverse out)))

(defun reference-bytes (form)
  (let ((src "/tmp/z80t.asm") (bin "/tmp/z80t.bin"))
    (with-open-file (s src :direction :output :if-exists :supersede)
      (format s "	~a~%" (insn->text form)))
    (sb-ext:run-program (or (sb-ext:posix-getenv "Z80ASM")
                            (concatenate 'string (or (sb-ext:posix-getenv "Z80PACK")
                                                     (concatenate 'string (sb-ext:posix-getenv "HOME") "/src/z80pack"))
                                         "/z80asm/z80asm"))
                        (list "-fb" (concatenate 'string "-o" bin) src) :output nil :error nil)
    (with-open-file (s bin :element-type '(unsigned-byte 8))
      (let ((v (make-array (file-length s) :element-type '(unsigned-byte 8)))) (read-sequence v s) v))))

(let ((pass 0) (fail 0))
  (dolist (f *cases*)
    (let ((mine (ignore-errors (assemble (list f)))) (ref (reference-bytes f)))
      (if (equalp mine ref) (incf pass)
          (progn (incf fail) (format t "MISMATCH ~a: ours ~x ref ~x~%" (insn->text f) mine ref)))))
  (format t "assembler: ~d passed, ~d failed, ~d total~%" pass fail (+ pass fail))
  (sb-ext:exit :code (if (zerop fail) 0 1)))
